### ISSUE TITLE
Question: eV to meV

### ISSUE THREAD

**Issue by shenoynikhil** [atomicarchitects/equiformer#1]
Hi there,

Great work and a super clean repository! I have a question about the target error values. So, QM9 dataset targets are in eV, whereas the reported errors in the paper are meV. Could you point me where this is happening in the repository?

**Comment by yilunliao** [comment]
Hi @shenoynikhil !

Thanks for your interest in the work.

I do not do the conversion in the code but do that manually. You can see some results in the training logs in the repository (i.e., Training -> QM9 -> 6.).

**Comment by shenoynikhil** [comment]
I was curious as your qm9 dataset file has the target values in eV, so is it like you calculate MAE on the eV values and then report 1000 * eV difference? I am referring to the logs [here](https://www.dropbox.com/sh/9yuah73ss9na8tw/AADb1iJXufqs0Zse_5DnuEPea/target%406?dl=0&preview=debug.log&subfolder_nav_tracking=1).

**Comment by yilunliao** [comment]
Yes. For the log you post, the file writes 0.00126 (eV), so I report 1.26 (meV).

**Comment by shenoynikhil** [comment]
Thanks a lot!
