### ISSUE TITLE
`task_mean` and `task_std` not used

### ISSUE THREAD

**Issue by shenoynikhil** [atomicarchitects/equiformer#11]
Are `task_mean` and `task_std` used anywhere during the training process?

**Comment by yilunliao** [comment]
Hi @shenoynikhil 

`task_mean` and `task_std` in [these lines](https://github.com/atomicarchitects/equiformer/blob/master/main_qm9.py#L145-L149) are used to normalize ground truth labels during training and denormalize predictions during inference.
