### ISSUE TITLE
Inquiry About Calculating AVG_DEGREE from Training Dataset

### ISSUE THREAD

**Issue by GaoShikun** [atomicarchitects/equiformer#17]
I hope this message finds you well. I am a graduate student currently studying with your project and have come across the value of AVG_DEGREE, which is approximately 15.57930850982666. I would like to understand how this value is derived from the training dataset.

Could you please explain how this value is calculated from the training dataset? Any insights, code snippets, or references to the relevant sections of the documentation would be greatly appreciated.

Thank you very much for your assistance!

**Comment by yilunliao** [comment]
Hi @GaoShikun 

Here is the short answer to your question.

I used the training set to compute `AVG_DEGREE`.
I computed the degrees of nodes in examples and then averaged over all examples (and nodes).
Note that `AVG_DEGREE` will depend on the cutoff radius and the maximum number of neighbors.

**Comment by GaoShikun** [comment]
> Hi @GaoShikun
> 
> Here is the short answer to your question.
> 
> I used the training set to compute `AVG_DEGREE`. I computed the degrees of nodes in examples and then averaged over all examples (and nodes). Note that `AVG_DEGREE` will depend on the cutoff radius and the maximum number of neighbors.

Thank you for your reply. I found the answer while reading the code, but I still appreciate your patient explanation.
