### ISSUE TITLE
Error: raise ProxySchemeUnknown(proxy.scheme) urllib3.exceptions.ProxySchemeUnknown: Proxy URL had no scheme, should start with http:// or https://**

### ISSUE THREAD

**Issue by utkarshp1161** [atomicarchitects/equiformer#3]
error in line 66 of file: datasets/pyg/qm9.py  while running sh scripts/train/qm9/equiformer/target@1.sh

raw_url = ('https://deepchemdata.s3-us-west-1.amazonaws.com/datasets/'
               'molnet_publish/qm9.zip')

What worked for me: remove '' from 'molnet_publish/qm9.zip'

finally : 
raw_url = ('https://deepchemdata.s3-us-west-1.amazonaws.com/datasets/molnet_publish/qm9.zip')

**Comment by yilunliao** [comment]
Hi @utkarshp1161 . 

Thanks for the comment. 
However, I can run the script without any error.
I check the [QM9 dataset in PyG](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/datasets/qm9.html) and find that they use the same `raw_url`.
Therefore, I think the current code should be free from error.
